### PR TITLE
feat(iOS): Support ZIP format

### LINKED ISSUE #382: iOS: Unable to use .zip files due to "The image does not have a valid mcu header" error
Impossible to upgrade with a .zip file du to the following error: "The image does not have a valid mcu header" on iOS

### PR DESCRIPTION
**Pull request by samuel-rl**
Allow users to use .zip file.

Use the same logic as IOS-nRF-Connect-Device-Manager : 
https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/blob/d46c9ff85c87e786e8550fc3f4d633b1bc5c67be/Example/Example/Util/McuMgrPackage.swift#L104

fix #382 

---------------------

Self Review:

* [ ] Appropriate test coverage
* [ ] Relevant Documentation updated

Smoke Tests:

* [x] Example app launches on iOS
* [x] Update with .zip file work on the Example app with iOS devices

### CODE REVIEW

**Comment by ball-hayden** [comment]
Thanks @samuel-rl - appreciate your contribution.

Can you confirm that using an older-style `app_update.bin` file still works as well, please?

(I don't see any reason why it wouldn't, to be fair).

Is there a reason why you chose to not read the manifest file?
I believe this is important for multi-image updates, which is the main motivation for using a `.zip` update bundle rather than the binary alone.

**Comment by samuel-rl** [comment]
> Thanks @samuel-rl - appreciate your contribution.
> 
> Can you confirm that using an older-style `app_update.bin` file still works as well, please?
> 
> (I don't see any reason why it wouldn't, to be fair).
> 
> Is there a reason why you chose to not read the manifest file? I believe this is important for multi-image updates, which is the main motivation for using a `.zip` update bundle rather than the binary alone.

You're right, I have copied/pasted the original code to check for the manifest file.

I had tested on iPhone 12 for both zip and bin files and it worked well. I'll also do a pr for Android. Maybe you can do a release candidate after that I'll be available this week to do more tests on real conditions.

**Comment by ball-hayden** [comment]
> I had tested on iPhone 12 for both zip and bin files and it worked well

Thank you.

> Maybe you can do a release candidate after that I'll be available this week to do more tests on real conditions.

It's an auto-generated release, so you'll get a full release straight after this PR.

Definitely welcome an Android PR as well.

**Comment by ball-hayden** [comment]
Oh, actually, on that point:

I never enabled commitlint on this repo.

Please could you re-word your commits to follow the semantic commit format? We can probably squash this into one commit, as well:

(e.g. `feat(ios): Support ZIP format`)

**Review by ball-hayden — APPROVED** [review]

**Comment by ball-hayden** [comment]
Thank you 🎉

**Pull request merged**
